### PR TITLE
Fixed an edge case with Safari ("infinite" html5 audio -> the end event won't run)

### PR DESCRIPTION
**Pull request by golddranks**
Fixes https://github.com/goldfire/howler.js/issues/657 . I'm not well-versed with the codebase, so I tried to code only for the bugged case (checks to call `_ended()` only if the audio duration was indeed said to be infinite), but it might be, of course, that there is more related, unaccounted edge cases.

### CODE REVIEW

**Comment by golddranks** [comment]
In particular, I'm not sure about removing the event listener after the event is run. I did it because the other event listeners did so too. Are the `_node`s re-used (replayed)? After the end is reached, Safari updates the `_node.duration` to reflect the real duration, but of course this isn't reflected in `_parent._duration`, so that might cause problems. A review needed!

Btw. to reproducing Safari setting the duration to infinite isn't too easy: it happens to me only if I shut down the server, let the loading fail, and then boot it up, and try loading the same sound again. Safari then sends a `Range: 0-1` HTTP header, if to which the server doesn't respond correctly (or doesn't support Range requests), Safari sets the duration infinite.

**Comment by golddranks** [comment]
Okay, I did one change: it now checks if the duration was set to infinite, and updates the parent _duration field and the default sprite, so the subsequent calls to `play()` will end as normally.

**Comment by golddranks** [comment]
Rebased the commits on master. @goldfire, do you think you could pull these in? They fix an edge case on Safari.

**Comment by treborb** [comment]
This is still an issue on Safari. Could this fix be merged in please?

**Comment by golddranks** [comment]
I'd love to see this as merged too. I wonder if this project is abandoned / not maintained?

**Comment by goldfire** [comment]
@golddranks The project is definitely maintained and not abandoned. We've just gone through some major crunch with a big game launch on Steam last week and I've barely had time to think about anything else. I'll be catching up on howler issues/pr's in the coming weeks.

**Pull request merged**
