### PR TITLE
Add the option to set a custom 'sinkId' (audio output device)

### PR DESCRIPTION
**Pull request by fartek**
I needed this functionality for a project we were building, so I decided to add it to the library. Basically, when you create the Howl object, you add the parameter 'sinkId' and set it to the id of a custom audiooutput device (also set html5 to true). For more info on this: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

### CODE REVIEW

**Comment by goldfire** [comment]
Interesting, I hadn't heard about this until just now. As it stands right now, it would need to be added as its own plugin since the howler.js core needs to have full compatibility between HTML5 and Web Audio. I'd also like to see this get a little less "experimental," so I'll leave this for now and re-asses in the future. Thanks!

**Comment by ibc** [comment]
Hi, any update or planning for this feature?
Thanks.

**Comment by fartek** [comment]
Hey, I haven't been paying too much attention to this to this thread as we've ended up using my fork. Can anyone comment what's the current state regarding setting sink ids? @goldfire?

**Comment by xdumaine** [comment]
Related: https://github.com/WebAudio/web-audio-api/issues/445

**Comment by n3tman** [comment]
Thanks for this PR! Helped me understand how to edit the library, since I had the same problem.
Though I had to add some more lines to `Sound.prototype` methods `init` and `reset`:
```js
self._sinkId = parent._sinkId;
```

You might want to check [wavesurfer.js](https://github.com/katspaugh/wavesurfer.js) implementation of [setSinkID](https://github.com/katspaugh/wavesurfer.js/search?q=setsinkid):
- [WebAudio](https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L288)
- [MediaElement](https://github.com/katspaugh/wavesurfer.js/blob/master/src/mediaelement.js#L334)

**Pull request closed without merging**
