### PR TITLE
add support for CAFF audio files (Core Audio File Format)

### PR DESCRIPTION
**Pull request by obiot**
CAFF is the iPhone's native audio file format for uncompressed sounds
and the recommended format by Apple for short sound effects.

This might not be useful as such, but quite handy when bundling Howler
together with a wrapper like Ejecta

### CODE REVIEW

**Comment by obiot** [comment]
@goldfire looks like I screwed up with the pull request, so I will close this one. But my initial intention was to add the following to the codec list :
`caf: !!audioTest.canPlayType('audio/x-caf;').replace(/^no$/, ''),`

**Comment by obiot** [comment]
proper PR here : https://github.com/melonjs/howler.js/pull/4

**Comment by filerun** [comment]
FYI: Currently CAF files do not play with Howler in any browser.

**Comment by goldfire** [comment]
@filerun I don't have an easy way of testing this at the moment. The support for these are in Howler, so do you know if the browser is reporting false on `audio/x-caf` or something else?

**Comment by obiot** [comment]
This only works with Ejecta so far, and yes it does then return true for CAF files.

**Comment by filerun** [comment]
Chrome, Edge and Firefox report false.

**Pull request closed without merging**
