### PR TITLE
Fix: Sounds stop playing after context is interrupted (fixes #928)

### PR DESCRIPTION
**Pull request by alvov**
In Safari browser on iOS when browser tab loses focus the audio context gets interrupted. If during this inactivity the "_autoSuspend" timeout fires, Howler is set to the `suspending` state, but the `self.ctx.suspend()` promise gets rejected, so Howler is never switched to the `suspended` state (which would allow the `_autoResume` method to perform).

Steps to reproduce:
1. grab iPhone with iOS 11 or 12
1. start an application that uses Howler (`autoSuspend` property should be set to `true`)
1. play a sound up to the end, which should trigger the auto suspension timer
1. then switch from the browser to the home screen (or another app)
1. wait for 30 seconds until the suspension timer fires, then switch back to the browser
1. Howler is stuck in `suspending` state

### CODE REVIEW

**Comment by alvov** [comment]
@goldfire can you please take a look? it's a relatively small one 🙃

**Comment by alvov** [comment]
@goldfire I've added `interrupted` state handling as was discussed here https://github.com/goldfire/howler.js/pull/928#discussion_r258545912
please check this PR

**Comment by mmoss** [comment]
@goldfire any chance of getting this in?

**Comment by kurozael** [comment]
@goldfire is this being ignored? Because this is an issue for us in prod.

**Comment by kant2002** [comment]
@goldfire @kurozael any information when this will be merged in?

**Comment by abdurrahmancuce** [comment]
@goldfire why is this PR not merged? This is an issue for us in prod.

**Comment by kant2002** [comment]
@abdurrahmancuce you can use `@kant2002/howler` package which I have to publish to start using code from this PR.

**Comment by goldfire** [comment]
Sorry, I must have missed this one! Thanks for finding the solution to this. I've gotten it tested now and will have it released later today in 2.2.0.

**Comment by alvov** [comment]
@goldfire thank you very much!

**Pull request merged**
