### PR TITLE
Allow npm to install 2.0 branch

### PR DESCRIPTION
**Pull request by rasjani**
And use it as dependency without any extra build steps.

### CODE REVIEW

**Comment by rasjani** [comment]
Oh, #290 is duplicate of this, closing ..

**Comment by rasjani** [comment]
Actually, i just noticed that #290 is against goldfire/howler *master* branch, not 2.0 where the issue is, hence re-opening this and hoping to get this fixed

**Comment by gilesbutler** [comment]
+1 for this.

**Comment by fyockm** [comment]
Can you just publish to npm as howler@2.0.0-beta?

```
npm publish --tag beta
```

See http://carrot.is/coding/npm_prerelease for more info.

**Comment by fyockm** [comment]
Also, +1 to this PR.

**Comment by bluedaniel** [comment]
+1

**Comment by goldfire** [comment]
You can now install 2.0 from npm:

    npm install howler@2.0.0-beta1

**Comment by fyockm** [comment]
Thanks!

**Pull request merged**
