### PR TITLE
Exposing the progress event from the XHR request

### PR DESCRIPTION
**Pull request by ValterJunior**
- Created an event for listening to the download progress of an audio file when it is requested by using web audio API.
- Created a documentation for the event.

> There are two other pull requests opened for this feature: The first one (#815 ) has a fairly good documentation but it wasn't implemented following the standard event approach. The second one  (#930 ) was implemented correctly but there is no documentation updated for that. I created this one by doing it as recommended by this comment [here](https://github.com/goldfire/howler.js/pull/815#discussion_r148324852) and also following the documentation.

### CODE REVIEW

**Comment by rowild** [comment]
I'd like to upvote this and hope this will be merged soon!

**Comment by rowild** [comment]
Any reason why this issue is still not merged in the official release?

**Comment by ValterJunior** [comment]
Well, basically they claim that any event done for web audio API should also work for hml5 audio. The thing is that `loadBuffer` only exists for web audio API anyway. So I don't know why they deny this changes in first place.

**Comment by crazywire** [comment]
> Well, basically they claim that any event done for web audio API should also work for hml5 audio. The thing is that `loadBuffer` only exists for web audio API anyway. So I don't know why they deny this changes in first place.

I am going to implement this for both web audio API and html5. I have already completed the code. 
 I am in the testing phase now. Stay tuned.

**Comment by ValterJunior** [comment]
These changes have been included in this other PR #1142. I am closing this one here.

**Pull request closed without merging**
