### PR TITLE
Added custom headers parameter in init when using XHR to fetch audio

### PR DESCRIPTION
**Pull request by kalizi**
Needed to add Authorization header for streaming file by using JWT, so just added headers parameter in howler init this way:

```
var howl = new Howl( {
    src: ['http://www.example.it/protected/f1.mp3', 'http://www.example.it/protected/f2.mp3'],
    format: ['mp3'],
    html5: false,
    headers: [
        {
            name: 'Authorization',
            value: 'Bearer ' + token
        }
    ]
});
```

### CODE REVIEW

**Comment by Slurp** [comment]
Hi, 

Is there any idea when this does get merged?

**Comment by rowild** [comment]
Would like to know, too, when this is going to be merged! Thanks!

**Comment by golayp** [comment]
Is there a plan to include this feature yet ?

**Comment by RobAWarner** [comment]
Hi, I would also really appreciate this being merged.
I need to be able to provide an authorization header with the request.

**Comment by fgilio** [comment]
Any plans on merging this or a similar PR?

**Comment by v-margko** [comment]
Hi - joining the queue of those who is waiting for this PR check-in.
Do you have an estimate for that? I'd appreciate to use howler in our app but really need this functionality to work)

**Comment by golayp** [comment]
> Hi - joining the queue of those who is waiting for this PR check-in.
> Do you have an estimate for that? I'd appreciate to use howler in our app but really need this functionality to work)
I don't think it'll be merged one day... I've forked and made necessary adapations on my own long ago...

**Comment by v-margko** [comment]
> > Hi - joining the queue of those who is waiting for this PR check-in.
> > Do you have an estimate for that? I'd appreciate to use howler in our app but really need this functionality to work)
> > I don't think it'll be merged one day... I've forked and made necessary adapations on my own long ago...

hi, sorry, but did you plan to write an answer to me? or really wanted just to quote my question?)

**Comment by fgilio** [comment]
Haha if you look really closely he also wrote this:
> I don't think it'll be merged one day... I've forked and made necessary adapations on my own long ago...

**Comment by v-margko** [comment]
> Haha if you look really closely he also wrote this:
Oh.. I see X) thank you!

**Comment by Androsid** [comment]
@goldfire check out this merge. we really need these changes!

**Comment by fgilio** [comment]
It's happening! Thanks a lot!

**Pull request merged**
