### PR TITLE
.volume() is wrong after fade

### PR DESCRIPTION
**Pull request by Megabyteceer**
After short fades volume returns 0 or 1; After long fades volume() returns not exact real volume.

### CODE REVIEW

**Comment by Megabyteceer** [comment]
line 1245 - i think additional volume setting has no sense now because it will be already equal to 'to'.

**Comment by dagormz** [comment]
Came here to post the same issue. I am working on a project that involves fading, and then fading to zero. I am having to store the value I fade to initially as the sound.volume() is not correct. Any insight on this issue?

**Comment by Megabyteceer** [comment]
PR with fix is open, but no updates. I use external fix as you do.

**Comment by dagormz** [comment]
Just figured this out actually. sound.volume() will return 1 while sound.volume(soundID) will return the correct sound volume after a fade. This is an example code snippet:

```
var sound = new Howl({
      src: ['1.mp3']
});
var id = sound.play()
sound.fade(1, .5, 100, id)
sound.volume() // Will return 1
sound.volume(id) // Will return .5
```

Not sure if this is documented anywhere, but it has worked for me.

**Comment by Megabyteceer** [comment]
Fade makes wrong volume especially for short fade times. As example 5 ms.

**Comment by dagormz** [comment]
Do you have a sample of that? I just tried this with 5ms and 1ms and it worked both times when using the ID.

screen shot 2019-02-19 at 2 27 00 pm
screen shot 2019-02-19 at 2 28 18 pm

**Pull request merged**
