### PR TITLE
Default effects properties were not set, + minor fixes

### PR DESCRIPTION
**Pull request by luxigo**
1.
Default effects properties were not set in the HowlerGlobal object.

The HowlerGlobal object (window.Howler) is instantiated here:
https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L232

But it happends before HowlerGlobal.prototype.init is overrided here:
https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js#L25

Setting default effect properties in the HowlerGlobal.prototype solved the problem.

2.
self.ctx.listener.setOrientation was not set properly on https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js#L105

3.
There was a typo in coneOUterangle

4.
It was not possible to specify only a subset of the panner attributes (maybe it was on purpose ?.. take it or leave it)

### CODE REVIEW

**Comment by erichlof** [comment]
Hi @luxigo and @goldfire 
@luxigo Thanks for catching these errors.  I wanted to bring to your (and James') attention 2 more minor copy&paste errors.  
The first one is:
https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js#L308
I think it should be a '[2]' instead of a '[1]'.
The second one is:
https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js#L376
Same thing - should be a '[2]' instead of a '[1]'.

I have already changed my source file and I can confirm that luxigo's changes work great.  Thanks again! :)
-Erich

**Comment by goldfire** [comment]
Thanks for finding all of these, and sorry it took so long to get merged!

**Comment by goldfire** [comment]
@erichlof Thanks, just committed both of those fixes as well.

**Comment by erichlof** [comment]
@goldfire 
Hi James, no problem - thanks for merging!  Glad to see this library evolving.  It's the best web audio library out there IMO.

**Pull request merged**
