### PR TITLE
Implement feature #489

### PR DESCRIPTION
**Pull request by elvisvoer**
Hey guys,

I've implemented feature #489 
I haven't added it to the minified version. You should include a gulp script to ease that process. I can make a pull request with one if needed.

Cheers,
Elvis

### CODE REVIEW

**Comment by goldfire** [comment]
I think this would be something good to add. However, the problem with doing it this way is that it only works with Web Audio, and core has to have parity between Web Audio and HTML5 Audio.

**Comment by elvisvoer** [comment]
The on progress event objects returned by Web Audio and HTML5 Audio are different. For Web Audio it's a progress object (normal XHR progress object ) having loaded and total bytes. For HTML5 Audio you can get the buffer loaded progress in seconds. I think that can be implemented as a separate even listener.

**Comment by goldfire** [comment]
Right, but I think for the purposes of howler.js an attempt should be made to somehow normalize that. I'm putting anything that doesn't have parity between the two into plugins, but I believe (not having looked into it extensively yet) that there's probably a way to get something like this into core.

**Comment by acewf** [comment]
if howler is implementing html audio, you can get the progress by
"track.onprogress = function() {};"
but if XHR request is not exposed, you want be able to get this progress..

**Comment by jgranick** [comment]
I believe that right now, there is no way to know if an HTML5 audio file is fully loaded.

`readyState == 4` only means that it's ready to playback without delay. This is when (if I'm not mistaken) Howler will dispatch the "load" event.

If that is the case, then dispatching "progress" on HTML5 audio is not truly valuable. We can get the total play time of the sound, and the amount of time buffered, but that does not determine when the browser will decide to to be `readyState == 4`

On the other hand, not dispatching "progress" damages the quality of preload progress.

HTML5 audio could omit "progress" events entirely, or dispatch a progress event of 0, and a progress event later of 1 (on ready state), or some made up multiple of the sound's length.

**Comment by jgranick** [comment]
In other words, I propose that you expose "progress" for Web Audio

For HTML5 Audio, either "progress" can be omitted, or it can dispatch fake "progress" events based upon the amount of time loaded, and some multiplier (based on some average of how many bytes it takes per second of audio for files)

**Pull request closed without merging**
